{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOOJFHva5EPtQ0wGXTaVGrN",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/RohitKhobare/Design_And_Analysis_of_Algorithm/blob/main/DAA_LA4.cpp\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 106
        },
        "id": "y73x8U1RA1_n",
        "outputId": "6d41241a-5b16-4b0f-dc1d-87e6232fa2cd"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "SyntaxError",
          "evalue": "invalid syntax (29515954.py, line 9)",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"/tmp/ipykernel_722/29515954.py\"\u001b[0;36m, line \u001b[0;32m9\u001b[0m\n\u001b[0;31m    using namespace std;\u001b[0m\n\u001b[0m          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
          ]
        }
      ],
      "source": [
        "#include <iostream>\n",
        "#include <vector>\n",
        "#include <algorithm>\n",
        "#include <queue>\n",
        "#include <chrono>\n",
        "#include <iomanip>\n",
        "#include <cstdlib>\n",
        "\n",
        "using namespace std;\n",
        "using namespace std::chrono;\n",
        "\n",
        "// Structure for items in Branch and Bound\n",
        "struct Item {\n",
        "    int id;\n",
        "    int weight;\n",
        "    int value;\n",
        "    double ratio;\n",
        "};\n",
        "\n",
        "// Comparator for sorting items by ratio descending\n",
        "bool compareItems(Item a, Item b) {\n",
        "    return a.ratio > b.ratio;\n",
        "}\n",
        "\n",
        "// Node for Branch and Bound state-space tree\n",
        "struct Node {\n",
        "    int level;\n",
        "    int profit;\n",
        "    int weight;\n",
        "    double bound;\n",
        "};\n",
        "\n",
        "// Comparator for Priority Queue (Max-heap based on bound)\n",
        "struct CompareNode {\n",
        "    bool operator()(Node const& n1, Node const& n2) {\n",
        "        return n1.bound < n2.bound;\n",
        "    }\n",
        "};\n",
        "\n",
        "// Upper bound calculation for Branch and Bound using Fractional Knapsack\n",
        "double calculateBound(Node u, int n, int W, const vector<Item>& items) {\n",
        "    if (u.weight >= W) return 0;\n",
        "\n",
        "    double profit_bound = u.profit;\n",
        "    int j = u.level + 1;\n",
        "    int totalweight = u.weight;\n",
        "\n",
        "    while ((j < n) && (totalweight + items[j].weight <= W)) {\n",
        "        totalweight += items[j].weight;\n",
        "        profit_bound += items[j].value;\n",
        "        j++;\n",
        "    }\n",
        "\n",
        "    if (j < n) {\n",
        "        profit_bound += (W - totalweight) * items[j].ratio;\n",
        "    }\n",
        "\n",
        "    return profit_bound;\n",
        "}\n",
        "\n",
        "// Dynamic Programming Implementation\n",
        "int knapsackDP(int W, const vector<int>& wt, const vector<int>& val, int n) {\n",
        "    vector<vector<int>> K(n + 1, vector<int>(W + 1, 0));\n",
        "\n",
        "    for (int i = 0; i <= n; i++) {\n",
        "        for (int w = 0; w <= W; w++) {\n",
        "            if (i == 0 || w == 0)\n",
        "                K[i][w] = 0;\n",
        "            else if (wt[i - 1] <= w)\n",
        "                K[i][w] = max(val[i - 1] + K[i - 1][w - wt[i - 1]], K[i - 1][w]);\n",
        "            else\n",
        "                K[i][w] = K[i - 1][w];\n",
        "        }\n",
        "    }\n",
        "    return K[n][W];\n",
        "}\n",
        "\n",
        "// Branch and Bound Implementation\n",
        "int knapsackBB(int W, const vector<int>& wt, const vector<int>& val, int n) {\n",
        "    vector<Item> items(n);\n",
        "    for (int i = 0; i < n; i++) {\n",
        "        items[i] = {i, wt[i], val[i], (double)val[i] / wt[i]};\n",
        "    }\n",
        "\n",
        "    sort(items.begin(), items.end(), compareItems);\n",
        "\n",
        "    priority_queue<Node, vector<Node>, CompareNode> Q;\n",
        "    Node u, v;\n",
        "\n",
        "    u.level = -1;\n",
        "    u.profit = 0;\n",
        "    u.weight = 0;\n",
        "    u.bound = calculateBound(u, n, W, items);\n",
        "\n",
        "    Q.push(u);\n",
        "    int maxProfit = 0;\n",
        "\n",
        "    while (!Q.empty()) {\n",
        "        u = Q.top();\n",
        "        Q.pop();\n",
        "\n",
        "        if (u.bound > maxProfit && u.level < n - 1) {\n",
        "            v.level = u.level + 1;\n",
        "\n",
        "            // Option 1: Include item v\n",
        "            v.weight = u.weight + items[v.level].weight;\n",
        "            v.profit = u.profit + items[v.level].value;\n",
        "\n",
        "            if (v.weight <= W && v.profit > maxProfit) {\n",
        "                maxProfit = v.profit;\n",
        "            }\n",
        "\n",
        "            v.bound = calculateBound(v, n, W, items);\n",
        "            if (v.bound > maxProfit) {\n",
        "                Q.push(v);\n",
        "            }\n",
        "\n",
        "            // Option 2: Exclude item v\n",
        "            v.weight = u.weight;\n",
        "            v.profit = u.profit;\n",
        "            v.bound = calculateBound(v, n, W, items);\n",
        "\n",
        "            if (v.bound > maxProfit) {\n",
        "                Q.push(v);\n",
        "            }\n",
        "        }\n",
        "    }\n",
        "    return maxProfit;\n",
        "}\n",
        "\n",
        "int main() {\n",
        "    // 5 Test cases with increasing Item Count (N) and Capacity (W)\n",
        "    vector<pair<int, int>> test_cases = {\n",
        "        {10, 50}, {20, 100}, {30, 200}, {40, 400}, {50, 800}\n",
        "    };\n",
        "\n",
        "    cout << \"=========================================================================================\\n\";\n",
        "    cout << \"                         0/1 KNAPSACK: DP vs BRANCH-AND-BOUND                           \\n\";\n",
        "    cout << \"=========================================================================================\\n\";\n",
        "    cout << left << setw(6) << \"Step\"\n",
        "         << setw(10) << \"Items(N)\"\n",
        "         << setw(14) << \"Capacity(W)\"\n",
        "         << setw(15) << \"DP Max Val\"\n",
        "         << setw(15) << \"DP Time(ms)\"\n",
        "         << setw(15) << \"B&B Max Val\"\n",
        "         << setw(15) << \"B&B Time(ms)\" << endl;\n",
        "    cout << \"-----------------------------------------------------------------------------------------\\n\";\n",
        "\n",
        "    srand(42);\n",
        "    int step = 1;\n",
        "\n",
        "    for (auto tc : test_cases) {\n",
        "        int n = tc.first;\n",
        "        int W = tc.second;\n",
        "\n",
        "        vector<int> wt(n), val(n);\n",
        "        for (int i = 0; i < n; i++) {\n",
        "            wt[i] = rand() % 20 + 1;\n",
        "            val[i] = rand() % 100 + 10;\n",
        "        }\n",
        "\n",
        "        // Benchmark DP\n",
        "        auto start_dp = high_resolution_clock::now();\n",
        "        int res_dp = knapsackDP(W, wt, val, n);\n",
        "        auto end_dp = high_resolution_clock::now();\n",
        "        double time_dp = duration<double, milli>(end_dp - start_dp).count();\n",
        "\n",
        "        // Benchmark Branch and Bound\n",
        "        auto start_bb = high_resolution_clock::now();\n",
        "        int res_bb = knapsackBB(W, wt, val, n);\n",
        "        auto end_bb = high_resolution_clock::now();\n",
        "        double time_bb = duration<double, milli>(end_bb - start_bb).count();\n",
        "\n",
        "        cout << left << setw(6) << step++\n",
        "             << setw(10) << n\n",
        "             << setw(14) << W\n",
        "             << setw(15) << res_dp\n",
        "             << setw(15) << fixed << setprecision(4) << time_dp\n",
        "             << setw(15) << res_bb\n",
        "             << setw(15) << fixed << setprecision(4) << time_bb << endl;\n",
        "    }\n",
        "    cout << \"=========================================================================================\\n\";\n",
        "\n",
        "    return 0;\n",
        "}"
      ]
    }
  ]
}