{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNp0s4JIICoDZRAm3CBMhKb",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/RohitKhobare/Design_And_Analysis_of_Algorithm/blob/main/DAA_LA5.cpp\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "cNdF-QbiCyMw"
      },
      "outputs": [],
      "source": [
        "#include <iostream>\n",
        "#include <vector>\n",
        "#include <cmath>\n",
        "#include <chrono>\n",
        "#include <iomanip>\n",
        "\n",
        "using namespace std;\n",
        "using namespace std::chrono;\n",
        "\n",
        "// Function to check if placing a queen at board[row][col] is safe\n",
        "bool isSafe(int row, int col, const vector<int>& board, int n) {\n",
        "    for (int i = 0; i < row; i++) {\n",
        "        // Check column safety and diagonal safety\n",
        "        if (board[i] == col || abs(board[i] - col) == abs(i - row)) {\n",
        "            return false;\n",
        "        }\n",
        "    }\n",
        "    return true;\n",
        "}\n",
        "\n",
        "// Backtracking function to place remaining queens\n",
        "bool solveNQueens(int row, int n, vector<int>& board, int fixedRow, int fixedCol) {\n",
        "    // Base Case: All rows processed successfully\n",
        "    if (row == n) {\n",
        "        return true;\n",
        "    }\n",
        "\n",
        "    // Skip the row where the first queen is pre-placed\n",
        "    if (row == fixedRow) {\n",
        "        return solveNQueens(row + 1, n, board, fixedRow, fixedCol);\n",
        "    }\n",
        "\n",
        "    // Try placing a queen in all columns for current row\n",
        "    for (int col = 0; col < n; col++) {\n",
        "        // Do not place in the pre-placed queen's column\n",
        "        if (col == fixedCol) continue;\n",
        "\n",
        "        if (isSafe(row, col, board, n)) {\n",
        "            board[row] = col; // Place queen\n",
        "\n",
        "            if (solveNQueens(row + 1, n, board, fixedRow, fixedCol)) {\n",
        "                return true; // Solution found\n",
        "            }\n",
        "\n",
        "            board[row] = -1; // Backtrack\n",
        "        }\n",
        "    }\n",
        "\n",
        "    return false; // No valid placement found\n",
        "}\n",
        "\n",
        "// Utility function to display the chessboard matrix\n",
        "void printBoard(const vector<int>& board, int n) {\n",
        "    for (int i = 0; i < n; i++) {\n",
        "        for (int j = 0; j < n; j++) {\n",
        "            if (board[i] == j) {\n",
        "                cout << \" Q \";\n",
        "            } else {\n",
        "                cout << \" . \";\n",
        "            }\n",
        "        }\n",
        "        cout << \"\\n\";\n",
        "    }\n",
        "}\n",
        "\n",
        "int main() {\n",
        "    // Test cases with increasing board dimensions (N)\n",
        "    vector<int> test_sizes = {4, 6, 8, 10, 12, 14, 15};\n",
        "    int fixedRow = 0; // Fix first queen at Row 0\n",
        "    int fixedCol = 0; // Fix first queen at Column 0\n",
        "\n",
        "    cout << \"=================================================================================\\n\";\n",
        "    cout << \"                   N-QUEENS BACKTRACKING BENCHMARK RESULTS                       \\n\";\n",
        "    cout << \"=================================================================================\\n\";\n",
        "    cout << left << setw(10) << \"Step\"\n",
        "         << setw(12) << \"Board (N)\"\n",
        "         << setw(20) << \"First Queen Pos\"\n",
        "         << setw(20) << \"Status\"\n",
        "         << setw(20) << \"Execution Time (ms)\" << endl;\n",
        "    cout << \"---------------------------------------------------------------------------------\\n\";\n",
        "\n",
        "    int step = 1;\n",
        "\n",
        "    for (int n : test_sizes) {\n",
        "        vector<int> board(n, -1);\n",
        "        board[fixedRow] = fixedCol; // Place first queen\n",
        "\n",
        "        auto start = high_resolution_clock::now();\n",
        "        bool solved = solveNQueens(0, n, board, fixedRow, fixedCol);\n",
        "        auto end = high_resolution_clock::now();\n",
        "\n",
        "        double exec_time = duration<double, milli>(end - start).count();\n",
        "\n",
        "        cout << left << setw(10) << step++\n",
        "             << setw(12) << (to_string(n) + \"x\" + to_string(n))\n",
        "             << setw(20) << (\"(\" + to_string(fixedRow) + \", \" + to_string(fixedCol) + \")\")\n",
        "             << setw(20) << (solved ? \"Solved\" : \"No Solution\")\n",
        "             << setw(20) << fixed << setprecision(4) << exec_time << endl;\n",
        "\n",
        "        // Display sample matrix output for N = 8\n",
        "        if (n == 8 && solved) {\n",
        "            cout << \"\\n--- Sample Board Output for 8-Queens (First Queen at (0,0)) ---\\n\";\n",
        "            printBoard(board, n);\n",
        "            cout << \"---------------------------------------------------------------\\n\\n\";\n",
        "        }\n",
        "    }\n",
        "    cout << \"=================================================================================\\n\";\n",
        "\n",
        "    return 0;\n",
        "}"
      ]
    }
  ]
}